### ISSUE TITLE
Request for software for managing pdf/scanned documents. 

### ISSUE THREAD

**Issue by id4vip** [gbbirkisson/spis#105]
Thanks for SPIS software, I am enjoying this software on my low end machine. I want to request the author of SPIS software please make pdf/scanned documents manager type of app with almost same type of functionality SPIS using. I do not want OCR type functionality/upload via web app. I just want almost SPIS type of functionality only 4-5 predefined fields to query the documents ( like user name, type of document, tag etc.).

**Comment by gbbirkisson** [comment]
It is nice to hear that SPIS is working well for you.

I created this software because I had a need for it personally. I chose to give it to the world because I have used so much FOSS software throughout the years, and I felt it was time for me to pay back a little to the world.

I have no need for a PDF/Document manager, so I have no incentive to build it. I am certainly not going to do that for free. The source for SPIS is open. You can adapt any piece of code there to fit your needs. Do with it what you will.

I will close this issue.

**Comment by id4vip** [comment]
Ok, thanks for reply & spis software.
