### ISSUE TITLE
[Request] Add authentification

### ISSUE THREAD

**Issue by parer55** [gbbirkisson/spis#110]
Anyway to add an Auth page? Would be incredibly useful. Thanks.

**Comment by gbbirkisson** [comment]
I will not add that feature to SPIS, because I want to offload that problem to the proxy in front of SPIS. You can for example configure nginx to do [basic](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/) or [LDAP/OAUTH](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-subrequest-authentication/) authentication.

**Comment by parer55** [comment]
OK, I understand. I already have it under Traefik, but I cannot use my bitwarden auto-fill with this type of Auth. Thus my question. Thanks anyway! Great work!
